Add Tests and little changes
stanislau93/tms_web_crawler pull request #2
Opened 2021-02-25 20:33 UTC by Aleksey4ik

2021-02-26 12:38 UTC, stanislau93 requested changes

2021-02-26 12:38 UTC, stanislau93 commented on Tests/ForumCrawlerTest.php
> +    public function testForumCrawler()
в тестах никогда не стоит полагаться на сторонний сервис. мы должны тестировать только наш собственный функционал. пример - топик под номером 19991115 может быть удален с сайта или структура комментариев поменяется. в идеале мы можем наши тесты выполнять оффлайн =)

ты подал мне идею - на следующей лекции посмотрим, как можно имитировать сторонние сервисы

а пока, я бы предложил разбить функцию crawl нашего сервиса как минимум на две - одна будет добывать элементы DomNode, а вторая - перерабатывать их в объекты класса Comment. так ты сможешь создать свои объекты DomNode и протестировать вторую функцию, не залезая вообще в интернет =)

2021-02-26 12:38 UTC, stanislau93 commented on Tests/FileStorageTest.php
> +        foreach ($this->comments as $key => $value) {
здесь похоже на простое дублирование кода из функции, которую мы пытаемся протестировать =)

я бы предложил передавать имя файла как свойство в класс FileStorageService. и в этом тесте тебе нужен объект класса FileStorageService, ведь именно его функционал мы тестируем. Т.е. в этом тесте было бы что то вроде

$storage = new FileStorageService();

$storage->setFilename('listCommentsForTest');

$storage->storeComments();

а потом можешь сравнить результат с тем файлом, который ты заготовил =)

2021-02-26 12:38 UTC, stanislau93 commented on Service/FileStorageService.php
> +            echo "Не могу открыть файл $file";
лучше throw Exception.

exit или die() - это плохая практика, т.к. он много вещей оставляет незавершенными (освобождение памяти, ответ на запрос с понятным сообщением ошибки и тд), если только у нас не совсем простой скрипт

2021-02-26 12:38 UTC, stanislau93 commented on Controller/CommentController.php
> +    public function fileStorage(array $comments): void
идея была в том, чтобы после запроса пользователя контроллер сам занимался сохранением. т.е. вызов storage объекта я бы добавил в первый метод

а возвращать вполне можно просто единичку. хотя твоя имплементация и не приведет к ошибкам

P.S. - а где вызывается метод fileStorage() ? или это на будущее?

P.P.S. всегда рекомендую называть методы в повелительных формах глаголов ( getFile - достань файл, storeToFile - сохрани в файл, crawlPage - ползи по странице ). за редким исключением это - негласное правило =)

2021-02-26 12:38 UTC, stanislau93 commented on Service/ForumCrawlerService.php
> +        // $domDoc->loadHTMLFile($url);                     //сыпал предупреждения: Warning: DOMDocument::loadHTMLFile(): htmlParseEntityRef: expecting ';'
комментарий в коде не нужен =) спасибо, что поправил. а что за предупреждения?

2021-02-26 12:38 UTC, stanislau93 commented on Service/ForumCrawlerService.php
> +        foreach ($elements as $key => $element) {
я не понимаю, почему он так себя ведёт. если будет время, попробую потестировать

$elements мы ищем по всей страничке - и находим 20 штук - это верно

НО - дальше мы ищем уже внутри одного единственного $element в каждой итерации. а у него внутри только один элемент с текстом и именем автора.

наверное, я не до конца понимаю метод query или xpath

2021-03-01 12:33 UTC, Aleksey4ik commented on Service/ForumCrawlerService.php
> +        // $domDoc->loadHTMLFile($url);                     //сыпал предупреждения: Warning: DOMDocument::loadHTMLFile(): htmlParseEntityRef: expecting ';'
caused by invalid syntax of the html document to load (probably an & (ampersand) used as parameter separator and not masked as entity with &).

2021-03-01 20:25 UTC, Aleksey4ik commented on Tests/ForumCrawlerTest.php
> +    public function testForumCrawler()
метод 'crawl' разбивать не стал)

2021-03-01 20:26 UTC, Aleksey4ik commented on Tests/FileStorageTest.php
> +        foreach ($this->comments as $key => $value) {
Тут я напортачил) Уже исправился, тесты переписал и запушил

2021-03-01 20:27 UTC, Aleksey4ik commented on Service/FileStorageService.php
> +            echo "Не могу открыть файл $file";
исправился)

2021-03-01 20:29 UTC, Aleksey4ik commented on Controller/CommentController.php
> +    public function fileStorage(array $comments): void
Добавил в форму чекбокс для возможности сохранения в файл, при его выборе, контроллер вызывает метод объекта FileStorageService

2021-03-02 17:27 UTC, stanislau93 approved these changes

2021-03-02 17:27 UTC, merged